name: azion-web-kit
on:
  push:
    branches:
      - UXE-1067--public-storybok
jobs:
  deploy:
    name: DEPLOY | prod
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3
        with:
          repository: aziontech/azion-web-kit
          ref: UXE-1067--public-storybok
          path: '.'
          clean: true
          fetch-depth: '0'
          lfs: 'false'
      - name: PRE INSTALL
        uses: actions/setup-node@v3
        with:
          node-version: 20.6.1
          registry-url: 'https://npm.pkg.github.com'
          scope: '@aziontech'
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_SECRET }}
      - name: INSTALLING DEPENDENCIES
        run: npm install
      - name: POST INSTALLING DEPENDENCIES
        run: npm run postinstall
      - name: BUILDING STORYBOOK
        run: npm run build-storybook
      - name: PREPARE TO DEPLOYMENT
        run: rm -rf vitest.config.js .storybook vite.config.js tailwind.config.cjs postcss.config.js pnpm-lock.yaml index.html CONTRIBUTING.md .prettierrc.json .eslintrc.cjs .nvmrc .github dist node_modules .editorconfig .gitignore docs primevue-sass-theme-3.40.1 LICENSE package-lock.json package.json post-install.sh README.md; cp -R storybook-static/* .
      - name: DEPLOYMENT STORYBOOK
        uses: patrickwyler/gcs-bucket-sync-action@1.3
        with:
          secrets: ${{ secrets.GCP_BUCKET_KEY }}
          bucket: ${{ secrets.GCP_BUCKET_NAME }}
