name: Release publish
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Release Package
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: aziontech/azion-web-kit
          ref: main
          path: '.'
          clean: true
          fetch-depth: '0'
          lfs: 'false'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.6.1
          registry-url: 'https://npm.pkg.github.com'
          scope: '@aziontech'
          always-auth: true

      - name: Github Package Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
